default:
  image: python:3.12-bookworm

stages:
  - test
  - lint

run_tests:
  stage: test
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry run pytest src/app -v

run_linter:
  stage: lint
  before_script:
    - pip install poetry
    - poetry install
  script:
    - poetry run flake8 src/app
